### ISSUE TITLE
Doxygen issue with duplicate header file names (on Windows)

### ISSUE THREAD

**Issue by lufriem** [robertosfield/website#3]
There's a minor issue with the doxygen generated documentation: it seems the vsg header files 
- 'include\vsg\nodes\Transform.h'
- 'include\vsg\maths\transform.h'

produced the same (?) doxygen file 'transform_8h_source.html' (note the lower case) which results in the following output on Windows when cloning the repo:

`warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'docs/ref/VulkanSceneGraph/html/Transform_8h_source.html'
  'docs/ref/VulkanSceneGraph/html/transform_8h_source.html'`

So this change will always show up as a 'local change'.

I just wanted to note this, I don't really think it's worth doing anything about it.

**Comment by robertosfield** [comment]
Might there be a doxygen hint to handle this problem?

**Comment by lufriem** [comment]
> Might there be a doxygen hint to handle this problem?

Doxygen [does in fact have a command](https://www.doxygen.nl/manual/config.html#cfg_case_sense_names) to handle case-(in)sensitive file systems, and I think CMAKE actually sets this correctly when generating documentation as part of the build process (on my Windows machine the 'Doxyfile.docs-vsg' file contains 'CASE_SENSE_NAMES       = NO'). So anyone generating the doxygen documentation locally should get a correct output

I think this really is just an artefact of the documentation being generated on a case-sensitive filesystem, then being comitted and finally cloned on a filesystem where it's not case sensitive. 

It works correctly on the website (https://vsg-dev.github.io/vsg-dev.io/ref/VulkanSceneGraph/html/Transform_8h_source.html vs https://vsg-dev.github.io/vsg-dev.io/ref/VulkanSceneGraph/html/transform_8h_source.html), which I guess is the primary use case.

These auto-generated HTML files should not be edited manually anyway, so it's really just something someone who's editing the website git repo on the Windows platform has to pay attention to.
